version: '3.5'

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-service
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./app:/app
    expose:
      - "80"
    networks:
      traefik: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN}`)"

networks:
  traefik:
    external: true
    name: traefik_default